//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTable
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ConID { get; set; }
    
        public virtual ConTable ConTable { get; set; }
    }
}
